/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as predixPollSol from "./PredixPoll.sol";
export type { predixPollSol };
import type * as predixMarketsSol from "./predixMarkets.sol";
export type { predixMarketsSol };
import type * as predixPredictionsSol from "./predixPredictions.sol";
export type { predixPredictionsSol };
export type { Lock } from "./Lock";
export type { MyContract } from "./MyContract";
export * as factories from "./factories";
export { Lock__factory } from "./factories/Lock__factory";
export { MyContract__factory } from "./factories/MyContract__factory";
export type { PredixPredictionMarket } from "./predixMarkets.sol/PredixPredictionMarket";
export { PredixPredictionMarket__factory } from "./factories/predixMarkets.sol/PredixPredictionMarket__factory";
export type { PredixPolls } from "./PredixPoll.sol/PredixPolls";
export { PredixPolls__factory } from "./factories/PredixPoll.sol/PredixPolls__factory";
