// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfvjxbpezwrxxqrwuecv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmdmp4YnBlendyeHhxcnd1ZWN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3NjIxNDUsImV4cCI6MjA1NDMzODE0NX0.Z6sX-AGRJnddbUDyiAHVD5VQcW_kY-kEeMhAw0bLbMc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);