/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as predixPollSol from "./PredixPoll.sol";
export * as predixMarketsSol from "./predixMarkets.sol";
export * as predixPredictionsSol from "./predixPredictions.sol";
export { Lock__factory } from "./Lock__factory";
export { MyContract__factory } from "./MyContract__factory";
